---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: test kibana web
      uri:
        url: "http://{{ ansible_nodename }}:5601"
        return_content: yes
      failed_when: "'AWESOME' not in this.content"
